### ISSUE TITLE
Weather Details are not accurate

### ISSUE THREAD

**Issue by myopenflixr** [Pirate-Weather/pirateweather#117]
Hello,

I wanted to report a couple discrepancies on what is being reported in Pirateweather versus AccuWeather.

Pirateweather is showing current wind speed at 78.62 mph (SSW). It is a bit windy today, but actual wind speed according to AccuWeather is only 7 mph (SSW) with Max Wind Gusts of 20 mph.

Pirateweather is also showing humidity at 76% and AccuWeather is only showing humidity at 68%

Temperature and Air Pressure look to be pretty accurate compared to AccuWeather

Just thought I'd share this with you.

Thanks,
Mike

**Comment by K-Money** [comment]
Hopefully this is the right place to add this. I've seen that the rain estimates have been extremely off in my area (e.g. predicting 11.31 inches of rain when merrysky.net says 1.2 and accuweather says 1.02). We don't get rain very frequently, so I've tended to just use it as a binary indicator of if there will be rain or not, but it'd be great if we can identify why it's so off. I've looked for a consistent multiple or offset but it's nothing so direct as that sadly. The Merrysky.net info appears accurate, but when I run the service in home assistant I get back the mistaken rain values. Below is the service call, its response, and a screenshot of the merrysky info for the same duration. USA zip code 90706.

```
service: weather.get_forecasts
target:
  entity_id: weather.pirateweather
data:
  type: daily
response_variable: daily_forecast
```

```
weather.pirateweather:
  forecast:
    - datetime: "2023-12-18T08:00:00+00:00"
      condition: rainy
      precipitation_probability: 21
      cloud_coverage: 84
      wind_bearing: 173
      temperature: 73
      templow: 57
      wind_speed: 3.78
      precipitation: 0.27
      humidity: 58
    - datetime: "2023-12-19T08:00:00+00:00"
      condition: rainy
      precipitation_probability: 80
      cloud_coverage: 100
      wind_bearing: 140
      temperature: 63
      templow: 57
      wind_speed: 4.97
      precipitation: 2.61
      humidity: 91
    - datetime: "2023-12-20T08:00:00+00:00"
      condition: rainy
      precipitation_probability: 98
      cloud_coverage: 87
      wind_bearing: 131
      temperature: 62
      templow: 57
      wind_speed: 8.19
      precipitation: 6.47
      humidity: 82
    - datetime: "2023-12-21T08:00:00+00:00"
      condition: rainy
      precipitation_probability: 98
      cloud_coverage: 91
      wind_bearing: 101
      temperature: 60
      templow: 56
      wind_speed: 8.84
      precipitation: 11.31
      humidity: 83
    - datetime: "2023-12-22T08:00:00+00:00"
      condition: rainy
      precipitation_probability: 68
      cloud_coverage: 63
      wind_bearing: 181
      temperature: 63
      templow: 54
      wind_speed: 4.16
      precipitation: 2.45
      humidity: 68
    - datetime: "2023-12-23T08:00:00+00:00"
      condition: sunny
      precipitation_probability: 2
      cloud_coverage: 9
      wind_bearing: 104
      temperature: 61
      templow: 51
      wind_speed: 3.76
      precipitation: 0
      humidity: 57
    - datetime: "2023-12-24T08:00:00+00:00"
      condition: sunny
      precipitation_probability: 1
      cloud_coverage: 5
      wind_bearing: 168
      temperature: 60
      templow: 51
      wind_speed: 3.65
      precipitation: 0
      humidity: 40
    - datetime: "2023-12-25T08:00:00+00:00"
      condition: sunny
      precipitation_probability: 3
      cloud_coverage: 12
      wind_bearing: 130
      temperature: 62
      templow: 54
      wind_speed: 4.07
      precipitation: 0
      humidity: 28
```



<html>
<body>

  | HA Precip Prob | HA Precip Amount | Merrysky.net Amount | Ratio | Offset
-- | -- | -- | -- | -- | --
12/18/23 | 21 | 0.27 | 0.04 | 6.75 | 0.23
12/19/23 | 80 | 2.61 | 0.03 | 87 | 2.58
12/20/23 | 98 | 6.47 | 0.7 | 9.24 | 5.77
12/21/23 | 98 | 11.31 | 1.2 | 9.425 | 10.11
12/22/23 | 68 | 2.45 | 0.2 | 12.25 | 2.25
12/23/23 | 2 | 0 | 0 |   |  
12/24/23 | 1 | 0 | 0 |   |  
12/25/23 | 3 | 0 |   |   |  


</body>
</html>


![image](https://github.com/Pirate-Weather/pirateweather/assets/5406336/c8b943f6-6c41-4c19-a58f-bb84c6bfa0ff)
